### ISSUE TITLE
Use local checkout for pangeo-forge-runner call

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/deploy-recipe-action#11]
In this action, we have an `actions/checkout` step, so the action is running in a locally-checked-out copy of the feedstock repo. This makes fetching the repo over https redundant (and unnecessarily costly). So instead of:

https://github.com/pangeo-forge/deploy-recipe-action/blob/dd3d04555b0b00eaed4c7fd8c79daba1d0cf6a95/action/deploy_recipe.py#L46-L47

https://github.com/pangeo-forge/deploy-recipe-action/blob/dd3d04555b0b00eaed4c7fd8c79daba1d0cf6a95/action/deploy_recipe.py#L93-L94

I think we can save networking time and just do:

```python
"--repo=."
```

**Comment by yuvipanda** [comment]
Yay

**Comment by cisaacstern** [comment]
Noting this also means we do not need to pass a `--ref` arg, as AFAICT it is not used for local checkout, xref:

> https://github.com/pangeo-forge/pangeo-forge-runner/blob/750f5105fbc2a6e08b53dfeb3ef491e1da605ed6/pangeo_forge_runner/commands/base.py#L64-L65
