### ISSUE TITLE
Support comments in requirements.txt

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/deploy-recipe-action#12]
Failed parsing of requirements.txt in https://github.com/leap-stc/data-management/pull/33/commits/d30240acf6e0e2305ba8fdd33902c59a5e1964a4:

> https://github.com/leap-stc/data-management/actions/runs/5685911763/job/15411769228?pr=33#step:6:58

reveals that this logic for parsing requirements.txt

https://github.com/pangeo-forge/deploy-recipe-action/blob/dd3d04555b0b00eaed4c7fd8c79daba1d0cf6a95/action/deploy_recipe.py#L77-L80

is too naive.

We should refine that logic to parse requirements.txt's that have comments.

**Comment by yuvipanda** [comment]
Yeah, it should call out to `pip install -r <filename>` (rather than `pip install <list-of-packages>` on the commandline
