### ISSUE TITLE
Drop `pangeo/forge` image in favor of lighter base image

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/deploy-recipe-action#18]
https://github.com/pangeo-forge/pangeo-forge-runner/pull/90 drops use of the `pangeo/forge` image dependency in `pangeo-forge-runner` so we should probably do the same. This will allow us to keep pace with current beam releases, and should also speed up builds, which @jbusecke has reported are (unsurprisingly) slow. This should be pretty simple to experiment with:

1. Choose a lighter image to update this line with

    https://github.com/pangeo-forge/deploy-recipe-action/blob/256da2916b5f17f358c5e5b0442458645cadb9f0/Dockerfile#L1

    Maybe read [this](https://pythonspeed.com/articles/base-image-python-docker-images/) or similar blog posts. Probably end up just trying one of [these](https://hub.docker.com/_/python)? 

2. Replace `quay.io/pangeo/forge:5e51a29` on that line with the URI for the chosen image tag
3. Now we don't have `conda`, so drop the `conda run -n notebook` from this line:

    https://github.com/pangeo-forge/deploy-recipe-action/blob/256da2916b5f17f358c5e5b0442458645cadb9f0/Dockerfile#L3

4. That might be all it takes?
5. Now make a PR with these changes, try running the action from `@pr-branch` and see if it works (and is faster).
6. We don't actually test the docker build in our testing here. Maybe do that before merge, I can help with that when we get to that point.

@jbusecke wanna give it a shot?

**Comment by jbusecke** [comment]
Yeah sure. Probably going to work off some backlog of stuff while the big request is running, but Ill assign myself and feel free to ping me if this does not move.
